version: 2 

project_name: skipper 

builds:
  - 
    env:
      - CGO_ENABLED=0 
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Env=PROD
brews:
  - name: skipper
    repository:
      owner: juandi247
      name: homebrew-skipper
    commit_author:
      name: Goreleaser Bot .
      email: juand.diaza@gmail.com
    description: "skipper is a tunnel and a reverse proxy..."
    homepage: "https://skipper.lat"
    license: "MIT"

chocolateys:
  - name: skipper
    title: Skipper Tunnel
    description: "skipper is a tunnel and a reverse proxy that enables you to share your localhost free using just a subdomain from the skipper.lat domain"
    tags: "reverse-proxy golang tunnels network protobuffers"
    authors: Juan Diego Diaz
    project_url: https://skipper.lat
    project_source_url: https://github.com/juandi247/Skipper
    # icon_url: "https://example.org/icon.png"  #todo: logo for later
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false 