on:
  push:
    branches:
      - tigerstyle-rewrite
    paths:
      - 'SkipperProxy/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: go to folder
        run: cd SkipperProxy
        
      - name: Run tests
        run: go test -v ./...

      # - name: Build binary
      #   run: go build -o Proxy

      # - name: Restart service
      #   run: sudo systemctl restart skipper.service
